chore(deps): Update pom.xml to include software.amazon.awssdk:dynamodb
aws/aws-encryption-sdk-java pull request #2041
Opened 2024-07-10 19:49 UTC by rishav-karanjit

*Issue #, if available:*
closes #2034 

*Description of changes:*
Update pom.xml to include software.amazon.awssdk:dynamodb

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

# Check any applicable:
- [ ] Were any files moved? Moving files changes their URL, which breaks all hyperlinks to the files.

2024-07-10 21:32 UTC, texastony requested changes

2024-07-10 21:32 UTC, texastony commented on README.md
> +  This library requires the AWS Cryptographic Material Providers Library in Java, and the KMS client from the AWS Java SDK V2.
Revert this.
See line 30, which covers this requirement.

2024-07-10 21:32 UTC, texastony commented on pom.xml
> +            <version>2.20.91</version>
You do not need to declare a version here.
Read https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/get-started.html
In particular, expand the POM.
```suggestion
```

2024-07-10 21:32 UTC, texastony commented on README.md
The README still has a mistake for the AWS SDK V1's KMS Version.

2024-09-09 21:34 UTC, closed without merging

2024-09-09 21:36 UTC, rishav-karanjit commented
The readme needs more fixes then just DDB