chore: source controlling cfn templates that will be used for our release process
aws/aws-encryption-sdk-java pull request #345
Opened 2021-09-22 22:22 UTC by josecorella

*Description of changes:*
code_artifact.yml and code_build_parameter_map.json are the same files that live in the [cfn](https://github.com/aws/private-aws-encryption-sdk-java-staging/tree/infra/cfn) branch of the private repos 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

# Check any applicable:
- [ ] Were any files moved? Moving files changes their URL, which breaks all hyperlinks to the files.

2021-09-22 23:15 UTC, texastony requested changes
Two thoughts:
1. There are no changes to the current infrastructure, correct? This is just documenting it.
2. Remove the metadata fields for cloud designer. 

Cloud Designer is a great tool for validating that the template is good. But it does add these meta tags that are not actually part of the stack.

2021-09-22 23:15 UTC, texastony commented on cfn/prod-release.yml
> +        id: 19b17bdc-5d49-4f12-93e6-6d761b7ce324
nit: Drop this

2021-09-22 23:15 UTC, texastony commented on cfn/prod-release.yml
> +        id: 894a45c5-5dc7-4f11-be65-8bf5e37e289d
Nit: drop this

2021-09-22 23:15 UTC, texastony commented on cfn/prod-release.yml
> +        id: 3dafd088-2792-4a41-b612-d9d049721644
nit: just do a text search for "AWS::CloudFormation::Designer" and drop these.

They are tags for the icons in the designer tool. They do not encode any information that is relevant to the CFN stack, and they will probably change if this is ever loaded into the designer again.

2021-09-22 23:22 UTC, josecorella commented
> Two thoughts:
> 
>     1. There are no changes to the current infrastructure, correct? This is just documenting it.
> 
>     2. Remove the metadata fields for cloud designer.
> 
> 
> Cloud Designer is a great tool for validating that the template is good. But it does add these meta tags that are not actually part of the stack.

1. No changes to the infrastructure. We had talked about adding the webhook settings here in the cfn but that will come in the next iteration of updates to our ci/cd process. Once we are comfortable with pressing the button to run the release we can see about adding the webhook.

2021-09-23 19:26 UTC, texastony approved these changes
Very nice!

2021-09-23 22:56 UTC, merged