chore: Adding semantic release config file
aws/aws-encryption-sdk-java pull request #346
Opened 2021-09-22 22:41 UTC by josecorella

*Description of changes:*
In order to automatically version and publish changelogs we will be using semantic-release to make our lives a lot easier. This file adds a configuration to track [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) both in the commit analyzer but in the changelog format.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

# Check any applicable:
- [ ] Were any files moved? Moving files changes their URL, which breaks all hyperlinks to the files.

2021-09-22 23:04 UTC, texastony commented
> In order to automatically version and publish changelogs we will be using semantic-release ~~to make our lives a lot easier~~ *to ensure a consistent versioning policy*. This file adds a configuration to track conventional commits both in the commit analyzer ~~but~~ *and* in the changelog format.

Nit: Changes to PR description

2021-09-22 23:05 UTC, texastony commented on .releaserc
> +                    {"type": "test", "hidden": true}
What about revert?

2021-09-22 23:07 UTC, texastony requested changes
Add revert and correct PR description. 
Also, what parses `.releaserc`? A Maven plugin? Can you reference the plugin in the PR description?

Sorry if I am being picky... I just don't want to be guessing.

2021-09-22 23:08 UTC, josecorella commented
> Add revert and correct PR description.
> Also, what parses `.releaserc`? A Maven plugin? Can you reference the plugin in the PR description?
> 
> Sorry if I am being picky... I just don't want to be guessing.

No worries these are great questions! [semantic-release](https://semantic-release.gitbook.io/semantic-release/) uses the .releaserc file in order to version and update changelogs

2021-09-22 23:20 UTC, texastony submitted a review, later dismissed
LGTM.

Not dead sure if "Bug Fixes" is correct for revert... but also not sure on what a better term is. If I see one in the wild, I'll cut a PR/share it with you and see what you think.

2021-09-22 23:24 UTC, josecorella commented
> LGTM.
> 
> Not dead sure if "Bug Fixes" is correct for revert... but also not sure on what a better term is. If I see one in the wild, I'll cut a PR/share it with you and see what you think.

yeah i was thinking of one too but saw that verdaccio for js-esdk used Bug Fixes for when we [reverted the last commit ](https://github.com/aws/aws-encryption-sdk-javascript/blob/master/CHANGELOG.md#303-2021-09-21)

2021-09-24 00:13 UTC, texastony approved these changes
LGTM: I assume we do not need a package.json... which is news to me.. but I am down with it.

2021-09-24 00:16 UTC, merged